name: CI

on:
  push:
    branches:
      - dev-Boris
  pull_request:
    branches:
      - dev-Boris

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Prettier globally
        run: npm install -g prettier

      - name: Prettify code
        run: prettier --write "**/*.{js,jsx,ts,tsx,md}"

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Create temporary package.json
        run: |
          echo '{
            "name": "temporary-project",
            "version": "1.0.0",
            "private": true,
            "devDependencies": {
              "eslint": "^9.2.0"
            }
          }' > package.json

      - name: Create ESLint configuration file
        run: |
          echo '{
            "env": {
              "browser": true,
              "es2021": true
            },
            "extends": "eslint:recommended",
            "parserOptions": {
              "ecmaVersion": 12,
              "sourceType": "module"
            },
            "rules": {}
          }' > .eslintrc.json

      - name: Verify ESLint configuration file
        run: cat .eslintrc.json

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint "**/*.js" --config .eslintrc.json --ignore-pattern "node_modules/*"

      - name: Clean up temporary files
        run: rm -rf package.json package-lock.json node_modules
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install HTMLProofer
        run: gem install html-proofer

      - name: Check HTML
        run: htmlproofer ./ --allow-missing-href
