name: CI

on:
  push:
    branches:
      - dev-Boris
  pull_request:
    branches:
      - dev-Boris

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Prettier globally
        run: npm install -g prettier

      - name: Prettify code
        run: prettier --write "**/*.{js,jsx,ts,tsx,md}"

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run JSHint
        run: jshint "**/*.js" --exclude node_modules

  super-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Super-linter
        uses: super-linter/super-linter@v6.5.0
        env:
          DEFAULT_BRANCH: dev-Boris
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTERS: "JAVASCRIPT,HTML"
          VALIDATE_ALL_CODEBASE: true

  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install HTMLProofer
        run: gem install html-proofer

      - name: Check HTML
        run: htmlproofer ./ --allow-missing-href
